### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by tomardern** [kensho/check-more-types#38]
Hi,

I'm attempting to use check-more-types within karma. I'm getting the following error:

 Uncaught TypeError: Cannot read property 'fn' of undefined
  at /node_modules/check-more-types/check-more-types.min.js:5

I'm a little stuck n this - any ideas?

Thanks,

**Comment by bahmutov** [comment]
I think this is missing check-types.js library - should be loaded before check-more-types.

**Comment by bahmutov** [comment]
Try using the latest check-more-types - I have removed the need for original check-types
