### ISSUE TITLE
ES+ Types

### ISSUE THREAD

**Issue by AutoSponge** [kensho/check-more-types#52]
I'm curious if there is an interest in adding support for [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) in `check.primitive` as well as types enabled by Symbol, like iterator.

**Comment by bahmutov** [comment]
Sure, not a bad idea, but hard to test across multiple Node versions though

**Comment by AutoSponge** [comment]
Wouldn't `check.primitive` just become: 
```js
function primitive(value) {
    var type = typeof value;
    return type === 'number' ||
      type === 'boolean' ||
      type === 'string' ||
      type === 'symbol';
  }
```

**Comment by bahmutov** [comment]
Yup, but testing it?

**Comment by AutoSponge** [comment]
A conditional test should work (may even work with a polyfill at this level): 

```js
if (typeof Symbol === 'function') {
  la(check.primitive(Symbol('test')), 'symbol');
}
```
