### ISSUE TITLE
npm cannot find the README

### ISSUE THREAD

**Issue by tleb** [kensho/check-more-types#59]
On [npm](https://www.npmjs.com/package/check-more-types):

> ERROR: No README data found!

Not a cache problem.
Was working a few days ago.
I can't see where it could come from.

**Comment by bahmutov** [comment]
Thanks for sending this, NPM sometimes messes up :( I had this happen for other packages (and they could not reliably reproduce or figure out why). I will try publishing again,

**Comment by bahmutov** [comment]
no, does not solve this problem, hmm

**Comment by bahmutov** [comment]
damn, ok, hope people use more `npm home check-more-types` than npm search. So unfortunate though, really sad.

**Comment by tleb** [comment]
I've sent a message to [the npm support](https://www.npmjs.com/support), we'll see what they have to say.

**Comment by bahmutov** [comment]
Thanks, I had filed issues about another project with missing README with them, and they could not figure out the issue :(

**Comment by tleb** [comment]
To keep you up to date:

> Hi Tleb, 

> Thanks for emailing, this is frustrating. I've notified the web team of this README issue and they are currently investigating. I'll be in touch in the next few days with an update. 

> Thanks so much, 
> Stephanie

**Comment by bahmutov** [comment]
Thank you!

On Tue, Mar 15, 2016 at 1:31 PM, tleb <notifications@github.com> wrote:

> To keep you up to date:
>
> Hi Tleb,
>
> Thanks for emailing, this is frustrating. I've notified the web team of
> this README issue and they are currently investigating. I'll be in touch in
> the next few days with an update.
>
> Thanks so much,
> Stephanie
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/kensho/check-more-types/issues/59#issuecomment-196938180>
>



-- 
Dr. Gleb Bahmutov, PhD

e: gleb@kensho.com
t: @bahmutov
w: http://glebbahmutov.com/
b: http://glebbahmutov.com/blog

**Comment by tleb** [comment]
I can't inform them on that:

> Hi Tleb, 

> We've been unable to figure out the exact cause why your readme isn't showing up. I'm wondering, could you describe what your release process is? It's probably an error somewhere in the publish process there. Knowing a bit more about how you publish will help the investigation. 

> Thanks so much, 
> Stephanie 

I let you contact them.

**Comment by bahmutov** [comment]
oh my, my publish process is npm publish :)
